Create extension to convert Source to Observable
bumble-tech/appyx pull request #99
Opened 2022-08-24 13:18 UTC by jlmd

## Description
Create extension to convert `Source<T>` to `Observable<T>`

## Check list

- [ ] I have updated `CHANGELOG.md` if required.
- [ ] I have updated documentation if required.

2022-08-24 13:27 UTC, KovalevAndrey approved these changes

2022-08-24 13:41 UTC, CherryPerry approved these changes

2022-08-24 13:43 UTC, LachlanMcKee requested changes
Would you mind writing a couple of tests to make sure this works?

2022-08-25 07:57 UTC, LachlanMcKee approved these changes
Thanks for adding the tests, and fixing the others not running!

2022-08-25 08:07 UTC, KovalevAndrey approved these changes

2022-08-25 10:25 UTC, merged